import { product } from './types/products.type'

export const sampleProducts: product[] = [
  {
    name: 'Adidas Slim tshit',
    slug: 'adidas-slim-tshirt',
    image: '../public/images/p1.jpg',
    category: 'tshirt',
    brand: 'Adidas',
    price: 10,
    countInStock: 20,
    description: 'High quality t-shirt',
    rating: 4.1,
    numReviews: 20,
  },
  {
    name: 'Lacoste pattern tshit',
    slug: 'laccoste-pattern-tshirt',
    image: '../public/images/p2.jpg',
    category: 'tshirt',
    brand: 'Lacoste',
    price: 13,
    countInStock: 24,
    description: 'High quality t-shirt',
    rating: 3.2,
    numReviews: 32,
  },
  {
    name: 'Lacoste jogger pant',
    slug: 'laccoste-jogger-pant',
    image: './public/images/p3.jpg',
    category: 'pant',
    brand: 'Lacoste',
    price: 20,
    countInStock: 32,
    description: 'High quality pants',
    rating: 4.9,
    numReviews: 10,
  },
  {
    name: 'Adidas slim pant',
    slug: 'adidas-slim-pant',
    image: '../public/images/p4.jpg',
    category: 'pants',
    brand: 'Adidas',
    price: 26,
    countInStock: 0,
    description: 'High quality pant',
    rating: 2.2,
    numReviews: 45,
  },
]
